version: '3.6'
services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      RAILS_ENV: development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: test12345
    ports:
      - 3000:3000
  db:
    image: postgres:12.6-alpine
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: test12345
